In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
full_CBI_df = pd.read_excel('data/CBDI3 All Evals for NSS.xlsx')
full_CBI_df.head()

,Child ID,Gender,Date of Birth,Location - Sub Level 1,contract number,Program Label,Adaptive Sum of Scaled Scores,Adaptive Developmental Quotient,Adaptive Percentile Rank,Adaptive 95% Confidence Interval,...,Code 1,Code 2,Code 3,Code 4,Code 5,Code 6,Code 7,Code 8,Code 9,Code 10
0,44879,F,2022-09-27,Southwest,contract 3,BDI-3 Eligibility Evaluation,7.0,85.0,16,77-97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,47795,F,2020-12-23,Greater Nashville,contract 2,BDI-3 Eligibility Evaluation,16.0,88.0,21,82-96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54340,M,2021-06-22,First Tennessee,contract 1,BDI-3 Eligibility Evaluation,8.0,90.0,25,81-101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,54344,F,2022-03-07,Southeast Tennessee,contract 1,BDI-3 Eligibility Evaluation,13.0,115.0,84,103-123,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,54515,M,2021-11-04,Memphis Delta,contract 3,BDI-3 Eligibility Evaluation,5.0,75.0,5,68-88,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
CBI_df = full_CBI_df.drop(['Code 1','Code 2','Code 3','Code 4','Code 5','Code 6','Code 7','Code 8','Code 9','Code 10'], axis=1)

In [45]:
duplicates = CBI_df[CBI_df.duplicated()]
duplicates.head()

Empty DataFrame
Columns: [Child ID, Gender, Date of Birth, Location - Sub Level 1, contract number, Program Label, Adaptive Sum of Scaled Scores, Adaptive Developmental Quotient, Adaptive Percentile Rank, Adaptive 95% Confidence Interval, Adaptive RDI, Adaptive Z-Score, Adaptive T-Score, Adaptive NCE, Social-Emotional Sum of Scaled Scores, Social-Emotional Developmental Quotient, Social-Emotional Percentile Rank, Social-Emotional 95% Confidence Interval, Social-Emotional RDI, Social-Emotional Z-Score, Social-Emotional T-Score, Social-Emotional NCE, Communication Sum of Scaled Scores, Communication Developmental Quotient, Communication Percentile Rank, Communication 95% Confidence Interval, Communication RDI, Communication Z-Score, Communication T-Score, Communication NCE, Motor Sum of Scaled Scores, Motor Developmental Quotient, Motor Percentile Rank, Motor 95% Confidence Interval, Motor RDI, Motor Z-Score, Motor T-Score, Motor NCE, Cognitive Sum of Scaled Scores, Cognitive Developmental Quotient, Cognitive Percentile Rank, Cognitive 95% Confidence Interval, Cognitive RDI, Cognitive Z-Score, Cognitive T-Score, Cognitive NCE, BDI-3 Total Sum of Scaled Scores, BDI-3 Total Developmental Quotient, BDI-3 Total Percentile Rank, BDI-3 Total 90% Confidence Interval, BDI-3 Total 95% Confidence Interval, BDI-3 Total Z-Score, BDI-3 Total T-Score, BDI-3 Total NCE, Adaptive-Self Care Examiner, Adaptive-Self Care Date of Testing, Adaptive-Self Care RS, Adaptive-Self Care SS, Adaptive-Self Care PR, Adaptive-Self Care AE, Adaptive-Self Care RDI, Adaptive-Self Care CSS, Adaptive-Self Care CSS 90%, Adaptive-Self Care Z-Score, Adaptive-Self Care T-Score, Adaptive-Self Care NCE, Adaptive-Personal Responsibility Examiner, Adaptive-Personal Responsibility Date of Testing, Adaptive-Personal Responsibility RS, Adaptive-Personal Responsibility SS, Adaptive-Personal Responsibility PR, Adaptive-Personal Responsibility AE, Adaptive-Personal Responsibility RDI, Adaptive-Personal Responsibility CSS, Adaptive-Personal Responsibility CSS 90%, Adaptive-Personal Responsibility Z-Score, Adaptive-Personal Responsibility T-Score, Adaptive-Personal Responsibility NCE, Social Emotional-Adult Interaction Examiner, Social Emotional-Adult Interaction Date of Testing, Social Emotional-Adult Interaction RS, Social Emotional-Adult Interaction SS, Social Emotional-Adult Interaction PR, Social Emotional-Adult Interaction AE, Social Emotional-Adult Interaction RDI, Social Emotional-Adult Interaction CSS, Social Emotional-Adult Interaction CSS 90%, Social Emotional-Adult Interaction Z-Score, Social Emotional-Adult Interaction T-Score, Social Emotional-Adult Interaction NCE, Social Emotional-Peer Interaction Examiner, Social Emotional-Peer Interaction Date of Testing, Social Emotional-Peer Interaction RS, Social Emotional-Peer Interaction SS, Social Emotional-Peer Interaction PR, Social Emotional-Peer Interaction AE, Social Emotional-Peer Interaction RDI, Social Emotional-Peer Interaction CSS, Social Emotional-Peer Interaction CSS 90%, Social Emotional-Peer Interaction Z-Score, ...]
Index: []

[0 rows x 210 columns]

In [33]:
CBI_df = CBI_df.drop_duplicates()

In [ ]:
# more cleaning

In [54]:
CBI_df['Adaptive RDI'].str.replace('<','',regex=False).str.replace('>','',regex=False)

0        39/90
1        79/90
2        77/90
3        99/90
4          NaN
         ...
23942    99/90
23943    96/90
23944    92/90
23945    66/90
23946    94/90
Name: Adaptive RDI, Length: 19500, dtype: object

In [39]:
CBI_eligible_df = CBI_df[CBI_df['Program Label'] == 'BDI-3 Eligibility Evaluation']

In [40]:
CBI_annual_df = CBI_df[CBI_df['Program Label'] == 'BDI-3 Annual Evaluation']

In [41]:
CBI_milestone_df = CBI_df[CBI_df['Program Label'] == 'BDI-3 Milestone or Exit Evaluation']